import { ROLES } from '../utils/constants';

export const navPermissions = {
  '/dashboard': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD, ROLES.EMPLOYEE, ROLES.AUDITOR],
  '/assets': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD, ROLES.AUDITOR],
  '/assets/allocation': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD],
  '/bookings': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD, ROLES.EMPLOYEE, ROLES.AUDITOR],
  '/maintenance': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD, ROLES.EMPLOYEE, ROLES.AUDITOR],
  '/audits': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.AUDITOR],
  '/reports': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.DEPARTMENT_HEAD, ROLES.AUDITOR],
  '/setup': [ROLES.ADMIN],
  '/logs': [ROLES.ADMIN, ROLES.ASSET_MANAGER, ROLES.AUDITOR],
};

export default navPermissions;
